---
loopback_ip: 1.1.1.1
role: PE
# Core-facing interfaces used for ISIS + LDP
core_ifaces:
  - GigabitEthernet0/0/0/0
  - GigabitEthernet0/0/0/1
# CE-facing bundle for all-active multihoming
aa_bundle_interface: Bundle-Ether1
esi: 0000.0000.0001.0001.0001
