---
loopback_ip: "1.1.1.12"
isis_net: "49.0001.0000.0000.0012.00"
role: "P"
core_ifaces:
  - name: "GigabitEthernet0/0/0/0"
    ip: "10.0.0.10/30"
  - name: "GigabitEthernet0/0/0/1"
    ip: "10.0.0.13/30"